# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70c94250d80906f4b79fcfc8b5f13f4f1685e547d21aa8da01399b69cd6626c6bff872e26b6e005cb9d97dfc9d66a5152523e18a67c9775a5758639c1826cea7

test:
  secret_key_base: c19ff0d1c9f577941af46b6316856d2cf2e443cbf3393c4d32ef7658a39ea98dfa26aa65fb5c743a37933a2a1ebc643011d8bfaea345ae7331b6603bee45d6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
